version: '3.8'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456  # 更改为您的密码
    ports:
      - 3000:3000

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'